# ------------------------------
# Grafana Alloy ConfigMap
# ------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: uatcmm
data:
  alloy.config: |
    logging {
      level = "info"
      format = "logfmt"
    }

    loki.source.file "springboot_logs" {
      targets = ["/logs/*.log"]
      labels = {
        job = "springboot-app"
      }
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

---
# ------------------------------
# Headless Service for StatefulSet
# ------------------------------
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-headless
  namespace: uatcmm
spec:
  clusterIP: None
  selector:
    app: springboot-app
  ports:
    - port: 4202
      targetPort: 4202

---
# ------------------------------
# NodePort Service (for NGINX)
# ------------------------------
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: uatcmm
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 4202
      targetPort: 4202
      nodePort: 30005  # Ensure this matches your NGINX proxy_pass config

---
# ------------------------------
# StatefulSet with Alloy Sidecar
# ------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: springboot-app
  namespace: uatcmm
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springboot-app
  serviceName: springboot-app-headless
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: tkgsharedharbor.corp.ad.sbi/idea-indents-dev/spring-test:2.0
          ports:
            - containerPort: 4202
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
        - name: alloy
          image: grafana/alloy:latest
          args:
            - run
            - /etc/alloy/alloy.config
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: app-logs
              mountPath: /logs
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
  volumeClaimTemplates:
    - metadata:
        name: app-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: your-storage-class-name  # 🔁 Replace with your actual StorageClass
        resources:
          requests:
            storage: 1Gi
